### ISSUE TITLE
how to run？

### ISSUE THREAD

**Issue by lyh9886** [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction#1]
怎么运行程序？

**Comment by jiaxiang-cheng** [comment]
> 怎么运行程序？

看readme

**Comment by lyh9886** [comment]
谢谢！！N_EPOCH的大小是不是会影响预测的准确度，是不是越大越好？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月2日(星期天) 晚上10:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1)





  
怎么运行程序？
  
看readme
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiaxiang-cheng** [comment]
> 谢谢！！N_EPOCH的大小是不是会影响预测的准确度，是不是越大越好？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction" ***@***.***&gt;; 发送时间:&nbsp;2022年1月2日(星期天) 晚上10:24 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1) 怎么运行程序？ 看readme — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

太小欠拟合，太大过拟合

**Comment by lyh9886** [comment]
你的代码里是不是只预测了fd001的数据




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月3日(星期一) 上午8:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1)





  
谢谢！！N_EPOCH的大小是不是会影响预测的准确度，是不是越大越好？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction" @.&gt;; 发送时间:&nbsp;2022年1月2日(星期天) 晚上10:24 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1) 怎么运行程序？ 看readme — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
太小欠拟合，太大过拟合
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiaxiang-cheng** [comment]
> 你的代码里是不是只预测了fd001的数据
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction" ***@***.***&gt;; 发送时间:&nbsp;2022年1月3日(星期一) 上午8:16 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1) 谢谢！！N_EPOCH的大小是不是会影响预测的准确度，是不是越大越好？ … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction" @.&gt;; 发送时间:&nbsp;2022年1月2日(星期天) 晚上10:24 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1) 怎么运行程序？ 看readme — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt; 太小欠拟合，太大过拟合 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我只预测了FD001，但也可以跑其他2-4

**Comment by lyh9886** [comment]
好的，谢谢！不要嫌我烦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月3日(星期一) 中午1:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1)





  
你的代码里是不是只预测了fd001的数据
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction" @.&gt;; 发送时间:&nbsp;2022年1月3日(星期一) 上午8:16 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1) 谢谢！！N_EPOCH的大小是不是会影响预测的准确度，是不是越大越好？ … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction" @.&gt;; 发送时间:&nbsp;2022年1月2日(星期天) 晚上10:24 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1) 怎么运行程序？ 看readme — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 太小欠拟合，太大过拟合 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt;
  
我只预测了FD001，但也可以跑其他2-4
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lyh9886** [comment]
有没有相关的论文可以借鉴呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月3日(星期一) 中午1:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1)





  
你的代码里是不是只预测了fd001的数据
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction" @.&gt;; 发送时间:&nbsp;2022年1月3日(星期一) 上午8:16 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1) 谢谢！！N_EPOCH的大小是不是会影响预测的准确度，是不是越大越好？ … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction" @.&gt;; 发送时间:&nbsp;2022年1月2日(星期天) 晚上10:24 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1) 怎么运行程序？ 看readme — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 太小欠拟合，太大过拟合 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt;
  
我只预测了FD001，但也可以跑其他2-4
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiaxiang-cheng** [comment]
> 有没有相关的论文可以借鉴呢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction" ***@***.***&gt;; 发送时间:&nbsp;2022年1月3日(星期一) 中午1:30 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1) 你的代码里是不是只预测了fd001的数据 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction" @.&gt;; 发送时间:&nbsp;2022年1月3日(星期一) 上午8:16 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1) 谢谢！！N_EPOCH的大小是不是会影响预测的准确度，是不是越大越好？ … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction" @.&gt;; 发送时间:&nbsp;2022年1月2日(星期天) 晚上10:24 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1) 怎么运行程序？ 看readme — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 太小欠拟合，太大过拟合 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 我只预测了FD001，但也可以跑其他2-4 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

请稍微看下readme， Zheng, S., Ristovski, K., Farahat, A., & Gupta, C. (2017, June). Long short-term memory network for remaining useful life estimation.

**Comment by lyh9886** [comment]
太感谢了！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月3日(星期一) 下午3:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1)





  
有没有相关的论文可以借鉴呢
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction" @.&gt;; 发送时间:&nbsp;2022年1月3日(星期一) 中午1:30 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1) 你的代码里是不是只预测了fd001的数据 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction" @.&gt;; 发送时间:&nbsp;2022年1月3日(星期一) 上午8:16 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1) 谢谢！！N_EPOCH的大小是不是会影响预测的准确度，是不是越大越好？ … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction" @.&gt;; 发送时间:&nbsp;2022年1月2日(星期天) 晚上10:24 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1) 怎么运行程序？ 看readme — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 太小欠拟合，太大过拟合 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 我只预测了FD001，但也可以跑其他2-4 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
请稍微看下readme， Zheng, S., Ristovski, K., Farahat, A., &amp; Gupta, C. (2017, June). Long short-term memory network for remaining useful life estimation.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lyh9886** [comment]
你的代码里有没有计算score平均分数啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月3日(星期一) 下午3:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1)





  
有没有相关的论文可以借鉴呢
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction" @.&gt;; 发送时间:&nbsp;2022年1月3日(星期一) 中午1:30 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1) 你的代码里是不是只预测了fd001的数据 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction" @.&gt;; 发送时间:&nbsp;2022年1月3日(星期一) 上午8:16 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1) 谢谢！！N_EPOCH的大小是不是会影响预测的准确度，是不是越大越好？ … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction" @.&gt;; 发送时间:&nbsp;2022年1月2日(星期天) 晚上10:24 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1) 怎么运行程序？ 看readme — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 太小欠拟合，太大过拟合 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.&gt; 我只预测了FD001，但也可以跑其他2-4 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
请稍微看下readme， Zheng, S., Ristovski, K., Farahat, A., &amp; Gupta, C. (2017, June). Long short-term memory network for remaining useful life estimation.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiaxiang-cheng** [comment]
> 你的代码里有没有计算score平均分数啊

没有，只有RMSE

**Comment by lyh9886** [comment]
我发现预测fd002和fd004的rems至少都是五十多，而且图像几乎一条直线，应该怎么调整代码啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月4日(星期二) 上午9:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1)





  
你的代码里有没有计算score平均分数啊
  
没有，只有RMSE
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiaxiang-cheng** [comment]
> 我发现预测fd002和fd004的rems至少都是五十多，而且图像几乎一条直线，应该怎么调整代码啊

几乎一条直线说明严重欠拟合，没用充分训练

**Comment by lyh9886** [comment]
改模型的哪些参数能减小欠拟合呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月4日(星期二) 下午2:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1)





  
我发现预测fd002和fd004的rems至少都是五十多，而且图像几乎一条直线，应该怎么调整代码啊
  
几乎一条直线说明严重欠拟合，没用充分训练
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lyh9886** [comment]
最近刚接触RUL，看了你的代码，我发现我只能看懂数据处理部分，有时间你可以给我说说这个模型是怎么建立、训练和测试的吗？可能是因为我没学过吧，重要的代码我都看不懂




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月4日(星期二) 下午2:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiaxiang-cheng/PyTorch-LSTM-for-RUL-Prediction] how to run？ (Issue #1)





  
我发现预测fd002和fd004的rems至少都是五十多，而且图像几乎一条直线，应该怎么调整代码啊
  
几乎一条直线说明严重欠拟合，没用充分训练
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
